### ISSUE TITLE
Question on AE pretraining part

### ISSUE THREAD

**Issue by yjyoo3312** [yumeng5/TopClus#3]
https://github.com/yumeng5/TopClus/blob/01e22fb73262bc45d361ec9165bdadbd929ac9a5/src/trainer.py#L79

Thank you for sharing the code. As far as I understand, this stage only trains autoencoder parameters, so It seems that 

'''
Adam(filter(lambda p: p.requires_grad, model.parameters()), lr=self.args.lr)
'''
should be converted to 

'''
Adam(filter(lambda p: p.requires_grad, model.ae.parameters()), lr=self.args.lr).
'''

If it is not, please let me know.

**Comment by yumeng5** [comment]
Hi,

Your understanding is correct (only the autoencoder part is trained). However, the two code versions are actually equivalent. This is because the BERT backbone parameters are frozen (`requires_grad` set to False as shown below) and will not be updated by the optimizer anyways.

https://github.com/yumeng5/TopClus/blob/01e22fb73262bc45d361ec9165bdadbd929ac9a5/src/model.py#L59-L60

Thanks,
Yu

**Comment by yjyoo3312** [comment]
Ah, I missed the line 59-60. Thank you for the fast reply!
